# Generated by Django 4.1.5 on 2023-01-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('laptops', 'laptops'), ('smartphones', 'smartphones'), ('accessories', 'accessories')], max_length=50)),
            ],
        ),
    ]
